name: autorelease

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  ci-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v2

      - name: Install dependencies
        run: mise run install

      - name: Codegen
        run: mise run codegen

      - name: Check for changes
        id: git-check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore: update generated code"
          body: "This PR updates the generated code."
          branch: "chore/codegen-update"
          base: "${{ github.head_ref || github.ref_name }}"
          commit-message: "chore: update generated code"

      - name: Run CI
        run: mise run ci

      - name: Release
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            gh release create ${{ github.ref_name }} --generate-notes
          else
            echo "Workflow dispatch triggered on non-tag ref. Skipping release creation."
          fi

      - name: Upload Artifacts
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: .
